// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT7VmkN2aB-cStgICpjnTDXT0vZYHcwnE',
    appId: '1:116124637798:web:c35e6ea5d9988a8d186ba7',
    messagingSenderId: '116124637798',
    projectId: 'beerbrewer-a7e42',
    authDomain: 'beerbrewer-a7e42.firebaseapp.com',
    storageBucket: 'beerbrewer-a7e42.appspot.com',
    measurementId: 'G-41B3NTD5KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_O6wT5HlgNoTbdPN57FvQ_vaXEG8lPZ0',
    appId: '1:116124637798:android:5e0c192db4aff6ce186ba7',
    messagingSenderId: '116124637798',
    projectId: 'beerbrewer-a7e42',
    storageBucket: 'beerbrewer-a7e42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw5M0ppkUkSAZwbhE1Ye33rPfGq4tF4_E',
    appId: '1:116124637798:ios:dddce925fcaf3b6a186ba7',
    messagingSenderId: '116124637798',
    projectId: 'beerbrewer-a7e42',
    storageBucket: 'beerbrewer-a7e42.appspot.com',
    iosClientId: '116124637798-o8fttemnh2sfglq1i1akvsubfe86i6fp.apps.googleusercontent.com',
    iosBundleId: 'com.tanjadejong.beerBrewer',
  );
}
